### ISSUE TITLE
`treeshake: false` breaks destructured namespace import

### ISSUE THREAD

**Issue by Skn0tt** [rollup/rollup#5899]
### Rollup Version

v4.39.0

### Operating System (or Browser)

Stackblitz

### Node Version (if applicable)

v18.20.3

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-tgg3m6ct

### Expected Behaviour

Running `npm run build && node dist/main.js` should pass, just like `node src/main.js` passes.

### Actual Behaviour

```js
TypeError: createContext is not a function
    at file:///home/projects/rollup-repro-tgg3m6ct/dist/main.js
    at async ModuleLoader.import (https://rollupreprotgg3m6ct-prno.w-corp-staticblitz.com/builtins.8cb5228f.js:154:2688)
    at async loadESM (https://rollupreprotgg3m6ct-prno.w-corp-staticblitz.com/builtins.8cb5228f.js:184:541)
    at async handleMainPromise (https://rollupreprotgg3m6ct-prno.w-corp-staticblitz.com/builtins.8cb5228f.js:165:296)

Node.js v18.20.3
```

The repro uses latest rollup, but I bisected this down to https://github.com/rollup/rollup/releases/tag/v4.34.5 being the first faulty release.
