### ISSUE TITLE
node.js (server-side) run through rollupjs transpiler imports lib/riot.js instead of lib/server/index.js

### ISSUE THREAD

**Issue by btakita** [rollup/rollup#1251]
`TypeError: riot$1.render is not a function`

I'm transpiling my server-side es6 code into es5 using rollup.

It looks like the `package.json` `jsnext:main` key is being used instead of `main` as expected.

**Comment by Rich-Harris** [comment]
you can configure rollup-plugin-node-resolve to only use `main`:

```js
nodeResolve({
  main: true,
  module: false,
  jsnext: false
})
```

It applies to all dependencies though, not sure if that's what you want. If necessary you can always link to the individual file:

```js
import riot from 'riot/lib/server/index.js';
```

**Comment by btakita** [comment]
Thank you.

`import riot from 'riot/lib/server/index.js';` causes it to work. Note that I have all files in node_modules set to be external, meaning they are not transpiled.

**Comment by GianlucaGuarini** [comment]
`riot.render` was never a part of the client side code http://riotjs.com/api/#rendering
<img width="448" alt="screen shot 2017-01-11 at 18 58 56" src="https://cloud.githubusercontent.com/assets/879612/21860228/0a0fdc64-d830-11e6-8ed4-d94d43a5105e.png">

Please check the rollup example to see how to configure riot with rollup.

**Comment by btakita** [comment]
This issue *is* occurring on the server side.

**Comment by snuggs** [comment]
MY MAN @Rich-Harris coming through. I told you @btakita this place is awesome. ;-)

**Comment by btakita** [comment]
Here's my rollup config. See the `$node__rollup` function

https://github.com/ctx-core/ctx-core/blob/master/rollup/lib.js

Again, it works with riotjs <= 3.0.5 & breaks with riotjs >= 3.0.6

**Comment by btakita** [comment]
This issue was fixed with https://github.com/rollup/rollup/issues/1258

**Comment by btakita** [comment]
Fixed by https://github.com/riot/riot/pull/2222

**Comment by Rich-Harris** [comment]
@btakita excellent — is it okay to close this issue, or is there anything left for Rollup to do? thanks

**Comment by GianlucaGuarini** [comment]
@Rich-Harris yes you can close this issue. I am not sure I am going to merge the patch though

**Comment by btakita** [comment]
@GianlucaGuarini Whatever you need to do to fix the issue I'm having :-/

**Comment by btakita** [comment]
@Rich-Harris Can you re-open the issue if @GianlucaGuarini decides not to merge the patch or does nothing to fix the issue?

**Comment by btakita** [comment]
@Rich-Harris btw, Svelte looks great. Are there plans on making it isomorphic?

**Comment by btakita** [comment]
To answer my own question, it is possible not to use `default` by ensuring that `default` is not present on the exported object. I guess it should be obvious...

See https://github.com/riot/riot/pull/2225
