### ISSUE TITLE
node.declaration.gatherPossibleValues is not a function

### ISSUE THREAD

**Issue by fczuardi** [rollup/rollup#957]
After upgrading rollup-plugin-commonjs from 4.1.0 to 5.0.3 I start getting this error:

```
node.declaration.gatherPossibleValues is not a function
TypeError: node.declaration.gatherPossibleValues is not a function
    at callHasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/nodes/shared/callHasEffects.js:51:23)
    at CallExpression.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/nodes/CallExpression.js:29:10)
    at Node.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:58:32)
    at ParenthesizedExpression.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:58:32)
    at Node.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:58:32)
    at VariableDeclarator.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/nodes/VariableDeclarator.js:54:33)
    at VariableDeclaration.hasEffects (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/ast/Node.js:54:27)
    at Module.run (/Users/fabricio/calamar/open/controltower/node_modules/rollup/src/Module.js:320:14)
    at /Users/fabricio/calamar/open/controltower/node_modules/rollup/src/Bundle.js:134:14
    at Array.forEach (native)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

I am still not sure if this is an issue with my config, with rollup or with rollup-plugin-commonjs, I will investigate it further and try to come up with a simplified test case, just pasting this here to raise a flag for now...

**Comment by Rich-Harris** [comment]
Sounds like a bug in Rollup itself that rollup-plugin-commonjs is simply exposing. If you're able to share a reproduction that would be very helpful, thank you

**Comment by fczuardi** [comment]
well, with  rollup-plugin-commonjs the bug dont happen, even with the latest versions of rollup…

I will take a look at what changed between 4.1.0 to 5.0.0 of rollup-plugin-commonjs...

the project that broke is using a browserify transform (sheetify) with rollup-plugin-browserify-transform plugin, and sheetify is know for not playing well with es6 imports, so I will try to filter further the root cause

**Comment by fczuardi** [comment]
I've found a workaround for this with a patch to sheetify that adds the option allowImportExportEverywhere: true to falafel / acorn so feel free to close this as invalid if you like :)

**Comment by matthieusieben** [comment]
This is due to issues with semi colons. Package writers use the coding style they want. However, when concatenating two files that do not have the same "semi-colon policy", the rollup bundle is broken. More info here #1004 .
