### ISSUE TITLE
Plugin throwing Error with numeric `code` causes TypeError within Rollup itself

### ISSUE THREAD

**Issue by nolanlawson** [rollup/rollup#5036]
### Rollup Version

3.25.1

### Operating System (or Browser)

MacOS

### Node Version (if applicable)

16

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-hc1mbx?file=rollup.config.js

### Expected Behaviour

When a plugin throws an error with a numeric code, like so:

```js
transform() {
  const error = new Error();
  error.code = 1234;
  throw error;
},
```

...  I would expect this to go through the normal Rollup plugin error reporting process.

### Actual Behaviour

An error is thrown from within Rollup itself:

```
TypeError: error.code.startsWith is not a function
```

This error comes from this line of code:

https://github.com/rollup/rollup/blob/63b712596b42c471d882b4de058d4647d3b9a55c/src/utils/logs.ts#L790

...and seems to have been introduced in 23c111c87145d15b0de032a6c7eeb6596764d1cf (Rollup v3.25.0).

The assumption seems to be that, if `error.code` is truthy, then it's a string type. However, a plugin may throw an Error with a numeric type for `error.code`.

**Comment by TrickyPi** [comment]
For customized errors in Plugin, I recommend using `this.error` api with type hints, it will tell us that Rollup expects `code` to be of type string.

**Comment by TrickyPi** [comment]
Hmm, fair enough.

**Comment by lukastaegert** [comment]
Yes, definitely an oversight. Unfortunately as I am travelling at the moment, fixing it will require at least another week.
