### PR TITLE
fix: a plugin error can contains numeric code

### LINKED ISSUE #5036: Plugin throwing Error with numeric `code` causes TypeError within Rollup itself
### Rollup Version

3.25.1

### Operating System (or Browser)

MacOS

### Node Version (if applicable)

16

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-hc1mbx?file=rollup.config.js

### Expected Behaviour

When a plugin throws an error with a numeric code, like so:

```js
transform() {
  const error = new Error();
  error.code = 1234;
  throw error;
},
```

...  I would expect this to go through the normal Rollup plugin error reporting process.

### Actual Behaviour

An error is thrown from within Rollup itself:

```
TypeError: error.code.startsWith is not a function
```

This error comes from this line of code:

https://github.com/rollup/rollup/blob/63b712596b42c471d882b4de058d4647d3b9a55c/src/utils/logs.ts#L790

...and seems to have been introduced in 23c111c87145d15b0de032a6c7eeb6596764d1cf (Rollup v3.25.0).

The assumption seems to be that, if `error.code` is truthy, then it's a string type. However, a plugin may throw an Error with a numeric type for `error.code`.

### PR DESCRIPTION
**Pull request by TrickyPi**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
resolves #5036

### CODE REVIEW

**Review by lukastaegert — APPROVED** [review]
Thanks!
