### PR TITLE
Fix regressions

### LINKED ISSUE #1584: `await` without function call is dropped
Regression in 0.49.

```javascript
async function foo() {
	await bar;
	baz();
}

foo();
```

produces

```javascript
async function foo() {
	baz();
}

foo();
```

### LINKED ISSUE #1585: `if` containing only `return` is dropped
Regression in 0.49.

```javascript
function foo(x) {
	if (x) {
		return y;
	}
	bar();
}

foo(z);
```

produces

```javascript
function foo(x) {
	bar();
}

foo(z);
```

### LINKED ISSUE #1587: this.declaration.assignExpression is not a function
We get the following error during angular-seed build with new version 0.49

TypeError: this.declaration.assignExpression is not a function
    at Node.assignExpression (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:6781:21)
    at Node.bind (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:5971:13)
    at eachChild.child (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:5670:34)
    at keys.forEach.key (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:5681:5)
    at Array.forEach (native)
    at Node.eachChild (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:5674:13)
    at Node.bind (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:5670:8)
    at body.forEach.node (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:6038:35)
    at Array.forEach (native)
    at Node.bind (C:\Git\PIM\Pim.Solution\Pim.PortalApp\node_modules\rollup\dist\rollup.js:6038:13)

Our gulp task is:

```
import Config from '../../config';
import { writeFile } from 'fs';
import { join } from 'path';

const globals = require('rollup-plugin-node-globals');
const builtins = require('rollup-plugin-node-builtins');

const nodeResolve = require('rollup-plugin-node-resolve');
const commonjs = require('rollup-plugin-commonjs');
const includePaths = require('rollup-plugin-includepaths');
const rollup = require('rollup');

const config = {
    input: join(Config.TMP_DIR, Config.BOOTSTRAP_FACTORY_PROD_MODULE),
    onwarn: function (warning: any) {
        // Suppress this error message... there are hundreds of them. Angular team says to ignore it.
        // https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
        if (warning.code === 'THIS_IS_UNDEFINED' || warning.code === 'NAMESPACE_CONFLICT') {
            return;
        }

        console.error(warning.code + ': ' + warning.message);
    },
    sourcemap: true,
    treeshake: true,
    name: 'main',
    plugins: [
        includePaths({
            include: {},
            paths: [join(Config.TMP_DIR, 'app')],
            external: [],
            extensions: ['.js', '.json', '.html', '.ts']
        }),
        nodeResolve({
            jsnext: true,
            main: true,
            module: true,
            preferBuiltins: true
        }),
        commonjs({ //See project.config.ts to extend
            include: Config.ROLLUP_INCLUDE_DIR,
            namedExports: Config.getRollupNamedExports()
        }),
        globals(),
        builtins()
    ]
};

export = (done: any) => {
    rollup.rollup(config)
        .then((bundle: any) => {
            return bundle.generate({
                format: 'iife'
            }).then((result: any) => {
                const path = join(Config.TMP_DIR, 'bundle.js');
                writeFile(path,
                    result.code,
                    (error: any) => {
                        if (error) {
                            console.error(error);
                            process.exit(0);
                        }
                        done();
                    });
            });
        })
        .catch((error: any) => {
            console.error(error);
            process.exit(0);
        });
};

```

Is this a rollup error or some error in our own code?

### PR DESCRIPTION
**Pull request by lukastaegert**
This resolves #1584 and #1585 by introducing a new options parameter object describing the current execution path to `Node.hasEffects()` and similar functions.
For now, there are two options:
* `inNestedFunctionCall = false/true` tells us if we are looking at effects of statements inside a nested function call. If we are inside a function, then all return statements should be kept; however, they should not count as effects for nested function calls
* `inNestedBreakableStatement = false/true` tells us if we are looking at effects inside a nested loop or switch statement (i.e. something that can contain BreakStatements). If we are inside e.g. a switch statement, then break statements should never be omitted; however, they should not count as effects for nested switch statements/loops

It should also test for and fix #1587.

### CODE REVIEW

**Comment by Conduitry** [comment]
:+1: Using this branch on the project where I was seeing #1584 and #1585, I'm no longer having those issues.

**Comment by swernerx** [comment]
Wondering if this also has a positive effect on https://github.com/rollup/rollup/issues/1588

**Comment by lukastaegert** [comment]
It seems that #1588 is actually the same as #1585, so I am quite confident.

**Comment by lukastaegert** [comment]
Will resolve #1588

**Comment by lukastaegert** [comment]
Until this is merged, you should be able to install rollup from this pull request via
```json
"rollup": "rollup/rollup#pull/1586/head"
```
in your package.json

**Comment by Rich-Harris** [comment]
released as 0.49.1 — thank you!
